import { createFileRoute } from "@tanstack/react-router";
import { Reveal } from "@/components/motion/Reveal";
import { RevealImage } from "@/components/motion/RevealImage";
import { PageHero, SiteShell } from "@/components/site/Sections";
import { Eyebrow } from "@/components/site/SiteUi";
import aboutImg from "../assets/ag-about-how-we-work.jpg";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [{ title: "About AG Legal Group" }, { name: "description", content: "AG Legal Group provides clear, practical fixed-fee legal support for individuals and small businesses across England and Wales." }], links: [{ rel: "canonical", href: "/about" }] }), component: AboutPage });

function AboutPage(){return <SiteShell><PageHero eyebrow="About AG Legal Group" title={"Clear legal support.\nPractical next steps."} description="AG Legal Group was established to provide professional legal drafting and dispute support without unnecessary barriers, complexity or inflated costs."/><section className="grid grid-cols-1 border-b border-clause-border md:grid-cols-2"><div className="md:border-r md:border-clause-border"><RevealImage src={aboutImg} alt="Professional legal support environment" wrapperClassName="w-full" className="aspect-[5/6] w-full object-cover object-center md:aspect-square"/></div><div className="flex flex-col justify-center px-4 py-14 md:px-16 md:py-16"><Eyebrow>How we work</Eyebrow><p className="mt-6 font-grotesk text-[17px] leading-[1.75] text-clause-cream">We work with individuals and small businesses across England and Wales who want matters handled properly, efficiently and at a fair, transparent cost.</p><p className="mt-5 font-grotesk text-[15px] leading-[1.75] text-clause-muted md:text-[16px]">The focus is on well-structured, legally sound written work, practical dispute support and clear communication. Fixed-fee pricing is offered wherever possible so clients understand the cost from the outset.</p><p className="mt-5 font-grotesk text-[15px] leading-[1.75] text-clause-muted md:text-[16px]">Founder Arslahn Gillani brings over nine years' experience supporting individuals and small businesses, with particular focus on dispute support, contracts and written legal documents.</p></div></section></SiteShell>}
